from files.config import bot, admin
from files.data import stat_bot
text_uz = {
    "start": "<b>Assalomu alaykum!\nMen Instagram videolarini yuklab beruvchi botman.\nVideo havolasini yuboring, men esa yuklab beraman.😊</b>",
    "izoh": f"<b>📥 @{bot} orqali yuklab olindi</b>",
    "X_url_instagram": "<b>❌Bu havola orqali yuklab bolmadi</b>",
    "none_url": "<b>❌Faqat instagram post yoki reels havolasini yuboring</b>",
    "x_url": "<b>🔗Botga faqat havola yuboring</b>",
    "til": "🇺🇿Tilni o'zgartirish",
    "input_message": "<b>Xabarni kiriting</b>",
    "suc": "<b>✅{} foydalanuvchiga xabar yuborildi</b>",
    "downloading": "<b>📥Yuklanmoqda......</b>",
    "sending": "<b>🔜Yuborilmoqda....</b>",
    "id_error": f"<b>👤Foydalanuvchi ID raqami kiritilmagan.\nMasalan: {admin}</b>",
    "msg_error": "<b>👤Foydalanuvchiga yuborish kerak bo`lgan xabar kiritilmagan.</b>",
    "err": "<b>😔Nomalum hatolik sabab yuklab olib olmadi.</b>",
    "MediaEmpty": "<b>❗️Ushbu instagram postdagi videofileni yuklab olib bo`lmadi.</b>",
    "xato_nomalum": "<b>😔Texnik muommolar sababli yuklab bolmadi. Kamchiliklar uchun uzr soraymiz</b>",
    "music_none": "<b>⚠️ Afsuski musiqa topilmadi.</b>",
    "wait": "Kuting....",
    "btn_error": "<b>Tugmalar notogri kiritilagan\nExample | https://example.com</b>",
    "except": "❗️Hatolik yuz berdi",
    "admin": f"<b>👨‍💻Admin panelga xush kelibsiz!\n\n🤖Bu yerda bot admini qilishi mumkin bolgan imkoniyatlari ko`rsatilgan.\n📊Bot azolari soni: {stat_bot()}</b>",
}

text_kz = {
    "start": "<b>Сәлем!\nМен инстаграмдағы видеоларды жүктеп алатын ботпын.\nВидео сілтемесін жіберіңіз, жүктеп беремін😊</b>",
    "izoh": f"<b>📥 @{bot} арқылы жүктеп алынды</b>",
    "X_url_instagram": "<b>❌Осы сілтемеден жүктеп алу мүмкін емес</b>",
    "none_url": "<b>❌Тек инстаграм постын немесе ролик сілтемесін жіберіңіз</b>",
    "x_url": "<b>🔗Тек ботқа сілтеме жіберіңіз</b>",
    "til": "🇰🇿Тілді өзгерту",
    "input_message": "<b>Хабарды енгізіңіз</b>",
    "suc": "<b>✅Хабар жіберілді</b>",
    "downloading": "<b>📥Жүктелуде......</b>",
    "sending": "<b>🔜Жіберілуде....</b>",
    "id_error": f"<b>👤Пайдаланушы идентификаторы енгізілмеген.\nМысалы: {admin}</b>",
    "msg_error": "<b>👤Пайдаланушыға жіберілетін хабарлама енгізілмеген.</b>",
    "err": "<b>😔Белгісіз себептермен оны жүктеп алу мүмкін болмады.</b>",
    "MediaEmpty": "<b>❗️Осы Instagram жазбасындағы бейне файлды жүктеп алу мүмкін болмады.</b>",
    "xato_nomalum": "<b>😔Техникалық ақауларға байланысты жүктеп салу мүмкін болмады. Кемшіліктер үшін кешірім сұраймыз.</b>",
    "music_none": "<b>⚠️ Кешіріңіз, музыка табылмады.</b>",
    "wait": "Күтің....",
    "btn_error": "<b>Дұрыс емес перне басулары енгізілді\nМысалы | https://example.com</b>",
    "admin": f"<b>👨‍💻Админ панеліне қош келдіңіз!\n\n🤖Міне, бот әкімшісі жасай алатын опциялар.\n📊Бот мүшелерінің саны: {stat_bot()}<b>",
    "except": "❗️Қате орын алды",
}